"""
URL configuration for Agenda project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

# Django REST Framework router (automatically generates API routes)
from rest_framework.routers import DefaultRouter

# ViewSet that handles Agenda CRUD operations
from EntriesAgenda.views import AgendaViewSet

# Create router instance for API endpoints
router = DefaultRouter()

# Register Agenda endpoint -> creates /Agenda/ API routes automatically
router.register(r'Agenda', AgendaViewSet)
urlpatterns = [
    # Include all API routes generated by the router under /api/
    path('api/', include(router.urls)),
    # DRF login/logout interface for browsable API (development only)
    path('api-auth/', include('rest_framework.urls', namespace='rest_franework')),
    # Django admin panel
    path('admin/', admin.site.urls),
]

# Customize Django admin panel title/header
admin.site.site_header = 'Agenda'