# Generated by Django 6.0.4 on 2026-05-03 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Release', 'Release'), ('Reminder', 'Reminder'), ('Event', 'Event')], max_length=100)),
            ],
        ),
    ]
