# Generated by Django 6.0.4 on 2026-05-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntriesAgenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
